config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :statuses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: 'static_pages#index'
  get 'stats', to: 'static_pages#stats'
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
  validates :user_id, presence: true
  validates :challenge_id, presence: true
  validates_uniqueness_of :user_id, scope: [:challenge_id]

  belongs_to :user
  belongs_to :challenge

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :challenge
  has_many :statuses
  has_many :challenges, through: :statuses
  has_many :completed_challenges, -> {where(statuses:{passed:true})}, through: :statuses, source: :challenge
  has_many :failed_challenges, -> {where(statuses:{passed:false})}, through: :statuses, source: :challenge

  def self.set_challenge
  #go through each user
  #pick a random challenge
  #assign it to the user
    @users = User.all
    @users.each do |user|

      @random_challenge = Challenge.limit(1).order("RANDOM()")
      user.update_attribute(:challenge_id, @random_challenge.first.id)

    end

  end

  def has_completed_challenge?(id)
    return false if self.statuses.where(challenge_id: id).empty?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

   protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:challenge_id])
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @title = "_Challenge_A_Day"
  end

  def stats
    @title = "_Stats"
    @user = current_user
    @completed_challenges = @user.completed_challenges
    @statuses = @user.statuses
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def create
    @status = current_user.statuses.new(status_params)
    @status.challenge_id = current_challenge.id
    @status.complete_date = Date.today
    if @status.save
      redirect_to root_url
    else
      redirect_to root_url
    end


  end

  private
  def status_params
    params.require(:status).permit(:passed, :difficulty)
  end

  def current_challenge
    Challenge.find(current_user.challenge_id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneDay</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <div class=container>
      <% if notice %> <div class="alert alert-success"><%= notice %></div> <% end %>
      <% if alert %> <div class="alert alert-danger"><%= alert %></div> <% end %>
      <%= render 'shared/header' %>


      <%= yield %>
    </div>
















  </body>
</html>

app/views/shared/_header.html.erb
<% if !user_signed_in? %>

<ul class="nav justify-content-center">
  <li class="page-title">
    <h1> <%= @title %> </h1>
  </li>
  <li class="nav-item">
    <%= link_to "Sign In", new_user_session_url %>
  </li>
</ul>




<% else %>
  <ul class="nav justify-content-center">
    <li class="page-title">
      <h1> <%= @title %> </h1>
    </li>
    <li class="nav-item">
      <%= link_to "Log Out", destroy_user_session_url, method: :delete %>
    </li>
    <li class="nav-item">
      <%= link_to "View Stats", stats_url %>
    </li>
  </ul>

<% end %>

app/views/static_pages/index.html.erb
<div class="container central-content">

<% if !user_signed_in? %>
  <h1> Accept the Challenge? </h1>

  </br>
  <%= link_to "Create an Account", new_user_registration_url, class: "btn btn-lg btn-secondary" %>
<% else %>
  <% if current_user.challenge != nil %>

    <% if current_user.has_completed_challenge?(current_user.challenge.id) %>
      <h3> Challenge Done! </h3>
      <h4> Come back tomorrow for a new one. </h4>
      <%= image_tag "tick.png" %>
    <% else %>
      <h3> <%= current_user.challenge.description %> </h3>

      <%= form_for Status.new do |f| %>
        <%= f.hidden_field :passed, value: true %>
        <%= f.hidden_field :difficulty, value: 1 %>
        <%= f.submit "Done!", class: "btn btn-lg btn-secondary"%>
      <% end %>
    <% end %>


  <% end %>
<% end %>

</div>

app/views/static_pages/stats.html.erb
<h1> Stats </h1>
<%= link_to "go back", root_url %>
<h4> <%= "Total Challenges Completed: #{@completed_challenges.count}" %> </h4>
<ul>
<% @completed_challenges.each do |challenge| %>
  <li>
    <h4><%= "Challenge #{challenge.id}" %></h4> </br>
    <%= "#{challenge.description}" %> <br>
    <%= "Completed on: #{@statuses.find_by(challenge_id: challenge.id).complete_date.to_formatted_s(:long_ordinal)}" %>
  </li>
<% end %>
</ul>